name: pedometer_example
description: Demonstrates how to use the pedometer plugin.
publish_to: "none"

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.0
  pedometer:
    # When depending on this package from a real application you should use:
    #   pedometer: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
