name: screen_state
description: A plugin for reporting screen events while the flutter application is running in background. Works for Android only.
version: 0.1.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/screen_state
author: CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: cachet.plugins.screenstate
    pluginClass: ScreenStatePlugin

