name: activity_recognition_flutter
description: Activity recognition plugin for Android and iOS.
version: 2.0.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages
author:  CACHET Team <cph.cachet@gmail.com>


environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_foreground_service: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.activity_recognition_flutter
        pluginClass: ActivityRecognitionFlutterPlugin
      ios:
        pluginClass: ActivityRecognitionFlutterPlugin


