name: weather
description: A weather plugin for fetching current weather and forecasting via the OpenWeatherMap API. Works for both Android and iOS.
version: 1.1.6
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/weather

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0

dev_dependencies:
  test: ^1.6.1

# The following section is specific to Flutter.
flutter: