name: noise_meter
description: A noise meter plugin for Android and iOS. Currently works for Android only, will support iOS in near future.
version: 0.0.1
author: CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_meter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: cachet.sensors.noisemeter
    pluginClass: NoiseMeterPlugin
