name: noise_meter
description: A Flutter plugin for collecting noise from the phone's microphone.
version: 4.0.0
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_meter

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_streamer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
