name: noise_meter
description: A Flutter plugin for collecting noise from the phone's microphone.
version: 5.1.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_meter

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audio_streamer: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
