name: screen_usage
description: A plugin for reporting screen events while the flutter application is running in background. Works for Android only.
version: 0.0.3
homepage: https://github.com/cph-cachet/screen_usage
author: CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: dk.cachet.screenusage
    pluginClass: ScreenUsagePlugin
