name: audio_streamer
description: Streaming of Pulse-code modulation (PCM) audio from Android and iOS
version: 1.3.0
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  permission_handler: ^5.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        androidPackage: plugins.cachet.audio_streamer
        pluginClass: AudioStreamerPlugin
      ios:
        pluginClass: SwiftAudioStreamerPlugin