name: mobility_features
description: Real-time mobility feature calculation
version: 1.2.0
homepage: https://github.com/cph-cachet/flutter-plugins/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_cluster: ^0.2.0
  stats: ^0.2.0+3
  path_provider: ^1.6.10


dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: