name: noise_level
version: 0.0.4
description: A noise mearusing plugin for Android and iOS. Currently works for Android only, will support iOS in near future.
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_level
author: CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: cachet.plugins.noise_level
    pluginClass: NoiseLevelPlugin

