name: mobility_features_example
description: An example app for the Mobility Features package.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 3.1.0

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobility_features:
    path: ../
  carp_background_location:
    ^4.0.0
    # path: ../../carp_background_location

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
